FROM python:3.10
RUN apt-get update \
  && apt-get -y install tesseract-ocr
  && sudo apt install rabbitmq-server
  && sudo apt install redis-server

ENV PYTHONUNBUFFERED 1
RUN mkdir core
COPY . /core/
WORKDIR /core
RUN pip install --upgrade pip
ADD ./requirements.txt /core/
RUN pip install -r requirements.txt
RUN chmod +x server_django.sh
RUN chmod +x worker_celery.sh
