FROM python:3.10
RUN apt-get update \
  && apt-get -y install tesseract-ocr && apt-get install ffmpeg libsm6 libxext6  -y

ENV PIP_ROOT_USER_ACTION=ignore
ENV PYTHONUNBUFFERED 1
RUN mkdir core
COPY . /core/
WORKDIR /core
RUN pip install --upgrade pip
ADD ./requirements.txt /core/
RUN pip install -r requirements.txt
RUN chmod +x server_django.sh
RUN chmod +x worker_celery.sh

