version: '3.3'

services:
  server:
    image: Web_app
    container_name: BloodTestResultWeb
    build:
      context: .
      dockerfile: DockerFile

    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/core/Main/static
    expose:
      - 8000
    environment:
        DEBUG: "True"
        CELERY_BROKER_URL: "redis://localhost:6379/0"
        CELERY_RESULT_BACKEND: "redis://localhost:6379/0"

  worker:
    image: Celery_app
    container_name: BloodTestResultCelery
    build:
      context: .
      dockerfile: DockerFile

    command: celery -A Blood_Test_Result worker -l info

    volumes:
        - static_volume:/core/Main/static
    environment:
      DEBUG: "True"
      CELERY_BROKER_URL: "redis://localhost:6379/0"
      CELERY_RESULT_BACKEND: "redis://localhost:6379/0"

    depends_on:
      - server
      - redis

  redis:
    image: redis:6.0.16-alpine 
    expose:
      - 6379

volumes:
  static_volume: {}

